### ISSUE TITLE
Add defined type to generally handle module installations and configuration

### ISSUE THREAD

**Issue by bobapple** [Icinga/puppet-icingaweb2#122]
The class `icingaweb2::module` can generally install, configure, enable and disable Icinga Web 2 modules. The installation is done by cloning a git repository. The user can decide what branch to use and if he wants to automatically update it.

It should be possible to install, configure and enable modules from the community with this defined type.

We need to keep in mind that at some point it will be possible to install modules from packages.icinga.com. In the future it will also be possible to install modules directly from exchange.icinga.com. Adding a `installation_method` may be a good thing here. However, it may also be better to add the installation method to each module.

**Comment by dnsmichi** [comment]
My fairly ugly hack, if it helps: https://github.com/Icinga/icinga-vagrant/blob/master/modules/icingaweb2/manifests/module.pp

I'm eagerly waiting for this feature so I can use the official module :)

**Comment by bobapple** [comment]
Added in 9d2a3d5429ffcf6e11ad8cc49162c6d1760a45bb
