### ISSUE TITLE
Please move development to master

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icingaweb2#134]
To let others track what's happening I'd really appreciate it if you could work on `master` instead of a `v2` branch.

Just retire the current master as `1.x`

This brings more transparency, and lets the users see whats happening. (And the way GitHub build its logic around it - e.g. closing issues with commit messages)

**Comment by bobapple** [comment]
You're right, I will take care of this as soon as time allows. 👍

**Comment by bobapple** [comment]
I merged the v2 branch into master. The previous code is located in v1.
