### ISSUE TITLE
Syntax error at 'resource_name'; expected '}'

### ISSUE THREAD

**Issue by lingfish** [Icinga/puppet-icingaweb2#136]
Attempting to use the current master, and getting:

```Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type icingaweb2::config::resource at /etc/puppet/manifests/site.pp:202 on node some.host```

The node def is:

```
  icingaweb2::config::resource { 'pgsql':
    ensure      => present,
    type        => 'db',
    db_type     => 'pgsql',
    host        => 'localhost',
    port        => '5432',
    db_name     => 'icingaweb2',
    db_username => 'icinga2',
    db_password => 'some_pass',
  }
```

This seems to be happening on some of your Travis builds too.

**Comment by bobapple** [comment]
This should be fixed in the current master, please let me know if not.
