### ISSUE TITLE
Missing Configuration

### ISSUE THREAD

**Issue by matthiasritter** [Icinga/puppet-icingaweb2#138]
Hi,
i've used this module from the beginning but since a few month there a some parameter missing.
- /etc/icingaweb2/module/monitoring --> there are some essential ini-Files which aren't configured anymore (commandtransports.ini; config.ini, backends.ini).
- Apache-Config is not set anymore

Will this settings be re-implemented in future?

Thanks

**Comment by dnsmichi** [comment]
I bet they will. `master` is currently in development, the old stable module is located in `v1`. I'm using that in one of our projects now too :)

**Comment by matthiasritter** [comment]
Hi @dnsmichi ,
thanks for the info. I think I missed the announcement for the new development for this module :-)
