### ISSUE TITLE
versions differ heavily .. ?

### ISSUE THREAD

**Issue by osimon** [Icinga/puppet-icingaweb2#139]
Guys, it seems the version on puppetforge is heavily differing from the one here at gitub .. 

This causes a really high effort when someone (like me) installs a version with "puppet module install .. " and then tries to follow the only documentation available in github where a lot of stuff isnt working anymore.. 

Or did I do a mistake ? When just cloning from github, what about the dependencies to other modules from puppetforge .. 

If I am wrong or doing wrong stuff, let me know, but at least my experience was really annoying.

regards

**Comment by lazyfrosch** [comment]
We are currently working on version 2.0.0, this will bring a lot of breaking changes.

See https://github.com/Icinga/puppet-icingaweb2/projects

Version 1.x.x is kept in the `v1` branch, but won't be maintained anymore.

Feel free to contribute.
