### ISSUE TITLE
Update version in Puppet Forge

### ISSUE THREAD

**Issue by martialblog** [Icinga/puppet-icingaweb2#141]
Hi,

the Module version in the Puppet Forge is quite old (Nov 2015), would be nice if you could update that version if possible. 

Cheers, 
Markus

**Comment by walterheck** [comment]
Can this happen sometime soon? It's quite the nuisance to have to pull in the source from github.

**Comment by martialblog** [comment]
I agree with @walterheck

**Comment by noqqe** [comment]
Why is nothing happening here? Cannot be this hard. Release is already there.

**Comment by bobapple** [comment]
https://forge.puppet.com/icinga/icingaweb2/2.0.0/readme
