### ISSUE TITLE
Icingaweb2 schema only created on second run when configured along with icinga2

### ISSUE THREAD

**Issue by yaron-idan** [Icinga/puppet-icingaweb2#144]
## Expected Behavior
Configuring icingaweb2 with this module, mysql schema should be created successfully upon the first time puppet configures the agent.
## Current Behavior
When applying the class for the first time on a puppet agent, importing the schema fails since the mysql user and db is not created yet. Upon running it a second time, it succeeds since the mysql objects are created later in the first run. This only happens when the module is used together with the icinga2 puppet module.
## Possible Solution
I expected requiring the mysql resource when invoking the icingaweb2 class would take care of this, but sadly I was mistaken. Chaining arrows also failed to do the trick.
## Steps to Reproduce (for bugs)
[This](https://gist.github.com/yaron-idan/6f3be9fe22e978f9546be6c3cb835af0) gist contains the two classes I'm using to configure icinga2 and icingaweb2, when running the icingaweb2 class directly I just check `manage_repo=true` and when running it via the init.pp class I check `manage_repo=false` in the icingaweb2 class.
## Your Environment

* Module version (`puppet module list`): 1.0.6
* Puppet version (`puppet -V`): 4.7.0
* Operating System and version:Ubuntu 16.04.2 LTS

**Comment by bobapple** [comment]
I can reproduce this, however I don't know why this is happening. I'll need some more time to test it carefully.

**Comment by yaron-idan** [comment]
Thanks for your reponse,
If the issue is reproduced, why is ןא closed? Was it solved somehow?

**Comment by bobapple** [comment]
Yes, 56e20212911601f64d387b728fea42d0534330f7 fixes the issue in master
