### ISSUE TITLE
Parameterize conf_user

### ISSUE THREAD

**Issue by leo-hf** [Icinga/puppet-icingaweb2#145]
Hi, 

Would be really helpful if we could define a web server user during install cause not everyone uses apache.

Something like:
class { 'icingaweb2':
      conf_user     => 'nginx',
}

Can you please consider implementing this feature?

Thanks,

**Comment by dgoetz** [comment]
For now this is limited by the packages requiring apache, but there are ongoing discussions to move to fpm which would allow changing the webserver more easy. I think waiting for this changes would make implementing this easier.

**Comment by bobapple** [comment]
We have already a `$conf_user` variable and would only need to make it configurable. We also initially planned to add nginx examples to the module. There are currently many other tasks I need to complete in this module, but I think I'll have a look at this once the module is 'more complete'

**Comment by leo-hf** [comment]
Thank you Bobapple, really appreciate it :)
