### ISSUE TITLE
add icingaweb2::module::puppetdb

### ISSUE THREAD

**Issue by rgevaert** [Icinga/puppet-icingaweb2#152]
Currently there is no native way to manage the puppetdb director module.

## Expected Behavior

Including ::icingaweb2::module::puppetdb would configure the puppetdb director module.

- It would enable/disable the module
- Set up the necessary certificates

## Current Behavior

You can configure it by using the native ::icingaweb2::module defined resource, and copying the ssl certificates in some way.

```
  icingaweb2::module { 'puppetdb':
    module_dir     => "${::icingaweb2::params::conf_dir}/puppetdb",
    git_repository => 'https://github.com/Icinga/icingaweb2-module-puppetdb',
  }

  file { "${::icingaweb2::params::conf_dir}/modules/puppetdb/ssl":
    ensure  => 'directory',
    group   => 'icingaweb2',
    mode    => '2750',
    owner   => 'www-data',
    recurse => true,
    source  => ...
  }
```

## Discussion needed

Writing the code for the module isn't a big deal.  The discussion that needs to take place is how to manage the ssl certificates needed to the integrate with the puppetdb(s).

The class should at the minimal set up the ssl subdirectory.  We could leave out the management of the SSL certificates as that is very environment specific.  E.g. some people would use hiera-eyaml. Other could use something else.

**Comment by bobapple** [comment]
I think the module needs multiple mechanisms to handle SSL certificates. The description in the official [docs](https://github.com/Icinga/icingaweb2-module-puppetdb/blob/master/doc/01-Installation.md) is not ideal, but we can work with it. I'd take some inspiration from the [icinga2](https://github.com/Icinga/puppet-icinga2) module ([API feature](https://github.com/Icinga/puppet-icinga2/blob/master/manifests/feature/api.pp), [IDO feature](https://github.com/Icinga/puppet-icinga2/blob/master/manifests/feature/idomysql.pp)).

I would think of a parameter `ssl` to let the user decide:
* `none`: create ssl directory only, let the user handle certificates himself
  * If `ssl_cert` and `ssl_key` is set, use the content to create the files.
* `puppet`: copy certificates from the puppet ssldir

What do you think?

**Comment by rgevaert** [comment]
Giving the user the choice is the best.  But...

My use case is that I need to have multiple puppetdbs to be queried.
* We could do this with passing a hash.  But that is also very error prone. And iterating through it is easy with Puppet 4, but not with Puppet 3.  create_resources can't be used because there is no icinga-certificate type.
* An other way out (which I think I could live with) is letting the module set up one certificate.  And then handle the second certificate outside of the module.

Or provide an extra defined type icingaweb2::monitoring::puppetdb::certificate. 

Summarizing: an ssl parameter that can take
* none: but with extra parameter certificates which expects hash of  icingaweb2::monitoring::puppetdb::certificate's. 
* puppet(default): copy from puppet ssldir

But I would understand adding  icingaweb2::monitoring::puppetdb::certificate would not be chosen.  I would be happy to work on this tomorrow (whatever consensus).  I want this upstream ;)

**Comment by bobapple** [comment]
Right, I didn't think of multiple PuppetDBs. I'd go with the hash variant you describe, including `icingaweb2::monitoring::puppetdb::certificate`
