### ISSUE TITLE
Icingaweb2::Module::Monitoring doesn't actually install the module

### ISSUE THREAD

**Issue by baurmatt** [Icinga/puppet-icingaweb2#160]
## Expected Behavior
If I include `Icingaweb2::Module::Monitoring` the monitoring module should be installed

## Current Behavior
The module expects that the system is configured to install recommended packages. If this isn't the case the monitoring module isn't installed.

## Possible Solution
Explicitly install the module which could be done by:
- Clone the git repository
- Installing the provide package (e.g. for Ubuntu 16.04 icingaweb2-module-monitoring)

## Steps to Reproduce (for bugs)
```bash
cat << EOF > /etc/apt/apt.conf.d/00recommended_suggested_packages
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF
```

```
class { '::icingaweb2':
  manage_repo => true,
}

class {'icingaweb2::module::monitoring':
  ido_host        => 'localhost',
  ido_db_name     => 'icinga2',
  ido_db_username => 'icinga2',
  ido_db_password => 'supersecret',
  commandtransports => {
    icinga2 => {
      transport => 'api',
      username  => 'root',
      password  => 'icinga',
    }
  }
}
```

--> Run Puppet.

## Context
Our environments run with recommends disable which leads to an incomplete installation of icingaweb2.

## Your Environment

* Module version (`puppet module list`): Current master (316b998ef7399155dd09e3ebd1ad15c85acefcc2)
* Puppet version (`puppet -V`): 4.10.3
* Operating System and version: Ubuntu 16.04.2

**Comment by baurmatt** [comment]
Seems like there aren't any packages for RedHat/CentOS/OpenSUSE/SLES, is this correct? I could only find icingaweb2-module-monitoring for Ubuntu/Debian.

I would suggest:
- Add both option (package and repo)
- Ubuntu/Debian defaults to package
- RedHat/CentOS/OpenSUSE/SLES defaults to git

**Comment by dgoetz** [comment]
Monitoring module is not a separate package for rpm based distributions, it is included in icingaweb2 package.
