### ISSUE TITLE
Dependency puppetlabs/concat conflicts with puppet-icinga2

### ISSUE THREAD

**Issue by cfoehrdes** [Icinga/puppet-icingaweb2#165]
The `puppetlabs/concat < 3.0.0` of puppet-icingaweb2 currently conflicts with `puppetlabs/concat < 5.0.0` of puppet-icinga2.

**Comment by cfoehrdes** [comment]
Just for your info, this also conflicts with the requirements of the current `puppet/nginx` release  which will probably be used by a lot of people to serve icingaweb2

**Comment by bobapple** [comment]
closed by 867728581d725d8d0b175508fdfde16d995bbae8
