### ISSUE TITLE
Store preferences in database

### ISSUE THREAD

**Issue by baurmatt** [Icinga/puppet-icingaweb2#166]
## Expected Behavior
Allow configuration of a [database as preference storage](https://github.com/Icinga/icingaweb2/blob/master/doc/07-Preferences.md#store-preferences-in-a-database-).

## Current Behavior
It is currently [not configurable](https://github.com/Icinga/puppet-icingaweb2/blob/master/manifests/config.pp#L22).

## Possible Solution
- Add parameter `icingaweb2::preferences_type` which defaults to **ini**
- If `icingaweb2::preferences_type` is set to **db** and `import_schema` is **true** add `resource = $db_type-icingaweb2` to `Icingaweb2::Inisection['preferences']`

Open Question: What happens if `import_schema` is **false** and the user wants to manage its database resource them self? I suggest adding an additional parameter `icingaweb2::preference_resource`. 

## Steps to Reproduce (for bugs)
Try to change the preference storage to database

## Context
We want to run a clustered IcingaWeb2 setup which make it a hard requirement to not a have any local configuration storage.

## Your Environment

* Module version (`puppet module list`): Current Master (2e19dfb217baedd8ac5268dd437d9437842a18e5)
* Puppet version (`puppet -V`): 4.10.1
* Operating System and version: Ubuntu 16.04.2

**Comment by baurmatt** [comment]
I'm happy to implement this, just need to known what you think about the possible solution.

**Comment by bobapple** [comment]
I agree with the `icingaweb2::preferences_type` parameter that defaults to `ini`. Regarding the schema import, we don't need a second import for `preferences.mysql.sql` because the table that stores preferences is already included in `mysql.schema.sql`. The documentation of Icinga Web 2 is wrong in this case, the behaviour has been changed without updating the docs.

Regarding your clustered Icinga Web 2: Storing preferences in a database is only implemented rudimentary in Icinga Web 2. You will still need many configuration files. The biggest issue I see with that is user dashboards. They are not stored in the database and we had many discussions about how to manage them with Puppet. If we should allow the user to update dashboards or not and so on. We still couldn't come up with a good solution. Anyway, this is another issue I'm just mentioning here.

**Comment by baurmatt** [comment]
Thanks for the clarification! :) With import_schema i meant that if the user wants to manage the database resources them self, they need to be able to specify it for the preference configuration:

```
[preferences]
type     = db
resource = icingaweb-mysql <<
```

Also thanks for the hint about problems with clustered IcingaWeb2 setups. I already found https://github.com/Icinga/icingaweb2/issues/1704 which requests the implementation of a database storage provider for dasboards.

**Comment by bobapple** [comment]
Alright, I think I got it. I'm not sure if this is really needed. If I'm using this module and I want to import the  schema, I have to configure the DB settings in the params, so actually you're "creating" the resource manually. If I don't want to import the schema, I'll have to add the resource manually. If I get it right, the option you want is "what if I want to import the schema, but add a custom db resource", but there is no difference in adding a resource manually and using the params that are already there. You know what I mean? Do I miss something?

**Comment by baurmatt** [comment]
The problem I see here is, that the $import_schema switch doesn't only import the schema it also configures:
- Database resources
- Auth method set to db
- Default user and role

At least the last two parts are not needed for our setup which is the reason we do not use `import_schema` and prefer to configure everything on our own. If the module would expect that the naming of the preferences database resource would be "icingaweb2-(mysqlpgsql)" i would need to name our custom database resource that way.

I see two ways to solve this:
- Add a parameter `icingaweb2::preference_resource` which allows to control the name of the preference database resource
- Mention in the README/comments that you have to name you database resource `icingaweb2-(mysqlpgsql)` if you want to enable the database storage for preferences.

Hope i made i clear what i think the problem is.

**Comment by baurmatt** [comment]
Which way do you prefer? I opt for the first one.

**Comment by bobapple** [comment]
I'm thinking of something like this:
* parameter `config_backend` that may be either `db` or `ini`
  * I like this better because this is what the setting is called in Icinga Web 2 
* if either `config_backend` is set to `db` or `import_schema` is set to `true`, the `icingaweb2-(mysql|pgsql)` resource is created, based on the `db_*` parameters
* Creation of default user and role would only happen if `import_schema` is true
  * `import_schema` may only be relevant for single node setups anyway

This would also solve your issue, right?

Creating the default user and role is something I think is helpful to get started quickly. The default role needs an ordering number, though.

An alternative would be a bunch of parameters like `create_default_user`, `create_default_role` etc. but I don't like the idea of overwhelming users with parameters.

**Comment by baurmatt** [comment]
>* parameter config_backend that may be either `db` or `ini`
> As far as I understood it, there is a difference between preferences/config.

(user) preferences (/etc/icingaweb2/preferences/*): Settings which the "normal" web interface user can set for himself. As this is can happen anytime, its critical in cluster setup to be stored in the db.
config (/etc/icingaweb2/config.ini): Global settings which only a administrator can change.

I just want to implement the (user) preferences. Global config should also be done, but it think this should be moved to another issue.

>* if either `config_backend` is set to `db` or `import_schema` is set to `true`, the `icingaweb2-(mysql|pgsql)` resource is created, based on the `db_*` parameters
>* Creation of default user and role would only happen if `import_schema` is true
> `import_schema` may only be relevant for single node setups anyway
>
>This would also solve your issue, right?

Kind of, it still doesn't explain how a user who do not use `import_schema` manages the resource name. Can you please take a look at #168, thats my idea of implementing this.  

>Creating the default user and role is something I think is helpful to get started quickly. The default role needs an ordering number, though
>An alternative would be a bunch of parameters like create_default_user, create_default_role etc. but I don't like the idea of overwhelming users with parameters.
A agree that there should be an easy way to use this module and also that there should be parameters for everything. The problem I see here is, that `import_schema` does a lot more than just "importing the schema" which is what the variable name implies. Perhaps we should solve this by only adding a good documentation of what to use as a default and add parameters for creating `(authmethod|groupbackend|resource|role)` objects.

**Comment by bobapple** [comment]
> As far as I understood it, there is a difference between preferences/config.

I think we have a misunderstanding here, which I didn't catch earlier, sorry for that. The `[preferences]` section in the `config.ini` file is not being used in the current Icinga Web 2 version anymore. It's an old concept of earlier versions, the resource in the `[global]` setting is the only valid setting in combination with `config_backend`. Therefore, it's not possible to set a different resource for user preferences. The Icinga Web 2 docs clearly need an update. 

The `preferences/` directory stores only user settings. Currently, this cannot be managed with this module. The directory will only be created and used if `config_backend` is set to `ini` and a user makes changes in the web interface.

After clarifying that, is my suggestion sufficient for your needs?

I agree that technically it would make sense to add a bunch of parameters, but I'm not sure about the usability. Maybe we could work with sane defaults to take over the work for users who want to get started quickly.

**Comment by baurmatt** [comment]
Ah, now i think we're getting closed :) Thanks for explaining, i've opened up https://github.com/Icinga/icingaweb2/issues/2950 to fix the documentation.

After knowing this, I still have some open question:
- Does `config_backend` do the same as `[preferences]` before? Or even more?
- Should `icingaweb2::inisection {'preferences':` be removed?
- Are you ok with what i implemented in #168 beside the fact that if should be `conifg_(backend|resource)` instead of `preferences_(backend|resource)`?

**Comment by bobapple** [comment]
> Does `config_backend` do the same as `[preferences]` before? Or even more?

It's the same as in `[preferences]`

> Should `icingaweb2::inisection {'preferences':` be removed?

Yes, I was a victim of the same trap

> Are you ok with what i implemented in #168 beside the fact that if should be `conifg_(backend|resource)` instead of `preferences_(backend|resource)`?

I'm still not sure how setting the name of the resource helps. If it's autogenerated it will be everywhere the same?

**Comment by baurmatt** [comment]
Thanks for clarifying! :)

>I'm still not sure how setting the name of the resource helps. If it's autogenerated it will be everywhere the same?

Even thought i propbably read your post about 10 times, i seem to have missed the fact that `config_backend = 'db'` would also generate the needed database resource.

I've updated #168 accordingly.
