### ISSUE TITLE
Logging directory is not created by module

### ISSUE THREAD

**Issue by yaron-idan** [Icinga/puppet-icingaweb2#172]
## Expected Behavior
Installing the module should create the logfile directory (`/var/log/icingaweb2` by default)
## Current Behavior
When using the module, the logging directory is not created, and therefore logs are not being written anywhere
## Possible Solution
Create the directory before setting the logging path
## Steps to Reproduce (for bugs)
1. Use the module to install icingaweb2 
2. Access the Configuration -> Application in the icingaweb2 UI
3. Try to save the current configuration
4. An error message saying `File path is not writable` will appear beneath the logging configuration, due to the absence of the logging dir.

## Context
As a workaround, I am creating the folder manually before running the module, but this seems like something the module can handle.
## Your Environment

* Module version (`puppet module list`): 1.0.6
* Puppet version (`puppet -V`): 4.7.0
* Operating System and version: 16.04.2 LTS

**Comment by baurmatt** [comment]
We're having the same problem. I've opened up #173 to fix this.
