### ISSUE TITLE
Add none to db_type parameter for class icingaweb2

### ISSUE THREAD

**Issue by lbetz** [Icinga/puppet-icingaweb2#175]
You can run Icinga Web 2 without a database backend, i.e. if you use LDAP as authentication backend. Maybe we should use a third enum like 'none' and this should be the default for db_type.

**Comment by lbetz** [comment]
Continue with setting default of import_schema to true like icinga2::feature::idoTYPE uses. Of course the schema must not included if db_type is 'none'.

**Comment by bobapple** [comment]
Do you mean `$config_backend = ini`?

**Comment by lbetz** [comment]
Ah, the parameter list isn't described completely... at the top of the init.pp.
