### ISSUE TITLE
[Feature Request] Add Grafana module

### ISSUE THREAD

**Issue by druchoo** [Icinga/puppet-icingaweb2#179]
Any chance of getting [Grafana module](https://github.com/Mikesch-mp/icingaweb2-module-grafana) added?

**Comment by druchoo** [comment]
Oops. Nevermind. Looks like icingaweb2::module can be used.

**Comment by baurmatt** [comment]
Would be great if you could share you implementation of the Grafana module with a PR. Guess a lot of people would like to configure it :)

**Comment by druchoo** [comment]
I'm working on it as we speak :-). I'll open back ticket so I don't forget and submit PR when I can.

**Comment by baurmatt** [comment]
Thanks! :)

**Comment by baurmatt** [comment]
Not sure what @bobapple means by this.

**Comment by bobapple** [comment]
Hope I could clarify it here: https://github.com/Icinga/puppet-icingaweb2/pull/133#issuecomment-335786225

I'm currently preparing the v2.0 release, fileshipper and vsphere are not high prio currently. However, I'm happy if you send a PR and will I merge it for v2.1!

**Comment by druchoo** [comment]
Hi @bobapple, I can provide examples manifests using icingaweb2::module. I just wasn't sure if that's what you guys wanted or if those modules would be incorporated with their own classes. Not sure how much time I'd have to devote to writing classes.

**Comment by bobapple** [comment]
@druchoo No preasure. I'll close this issue and open separate issues for fileshipper and vsphere.

Thank you for your contribution!
