### ISSUE TITLE
Add FreeBSD support

### ISSUE THREAD

**Issue by rick-pri** [Icinga/puppet-icingaweb2#190]
The `puppet-icinga2` module supports FreeBSD however, this project doesn't and I think that they should both support the same platforms since they will normally be used together.

**Comment by rick-pri** [comment]
You can track my attempts to add this **[here](https://github.com/rick-pri/puppet-icingaweb2/tree/feature/attempting-to-add-freebsd-support)**.

**Comment by lazyfrosch** [comment]
I guess we are open for PRs on that!

**Comment by rick-pri** [comment]
I've made some progress on this.  

I've also noted that the `icingacli` command on FreeBSD is different to everything else and that I'm going to have to add a path to the `director-migration` exec command so I need to know what other paths are required for the other OSes (else I'm going to have to put in nearly every conceivable path; e.g. `/bin` `/sbin` `/usr/bin` `/usr/sbin` `/usr/local/bin` `/usr/local/sbin` and the path on FreeBSD to the icingacli binary.)

Also, in the same manifest `./manifests/module/director.pp` check on `$import_schema` makes an assumption that there's an `icingacli` package which needs to be installed but this is included in the `icinga2` package on FreeBSD.  I think that I'll move this into the `params.pp` for now and set to undef for FreeBSD with a check on the variable.

Feedback on these approaches is welcome.  I'll have something up on my fork shortly.

**Comment by rick-pri** [comment]
https://github.com/Icinga/puppet-icingaweb2/pull/210
