### ISSUE TITLE
Setting up icingaweb2 with postgresql on a different port than 5432 leads to an error

### ISSUE THREAD

**Issue by Faffnir** [Icinga/puppet-icingaweb2#195]
When icingaweb2 is configured with a postgresql database which is serverd on a different port than 5432 it leads to errors as this [command](https://github.com/Icinga/puppet-icingaweb2/blob/80da5eca51bafd6cf2696d7c576c091d00da3e02/manifests/config.pp#L141) tries only to connect to port 5432.

Possibility would be to add -p <port-number> to the command but that also implies that the port is always set correctly according to the db_type.

What would anyone else suggest?

**Comment by bobapple** [comment]
Closed with c3632077f8e0ecabfba2355c34c1591f7b7ea9b9
