### ISSUE TITLE
Should be possible to specify a relative path for icingaweb2::module::fileshipper target

### ISSUE THREAD

**Issue by druchoo** [Icinga/puppet-icingaweb2#209]
## Expected Behavior

According to the docs it should be possible to specify a relative path for icingaweb2::module::fileshipper target. This places that dir under correct API path (/var/lib/icinga2/api/ by default)

https://github.com/Icinga/icingaweb2-module-fileshipper/blob/master/doc/04-FileShipping.md#plain-config-file-shipping
```
[custom-rules]
source = /usr/local/src/custom-rules.git
target = zones.d/director-global/custom-rules
```

## Current Behavior

It's only possible to specify an absolute path

**Comment by druchoo** [comment]
Actually, i see that the fileshipper module interprets a relative and absolute path the same. Feel free to close.

**Comment by dnsmichi** [comment]
You can do so too on GitHub :)
