### ISSUE TITLE
Hiera  create_resources() or better way

### ISSUE THREAD

**Issue by linuxmail** [Icinga/puppet-icingaweb2#211]
hi,

I had a very old icinga-icingaweb2 module running and upgraded today. I changed everything what is needed.

To manage the most parts in Hiera, I use the following construct:

master.pp

```
  # For resources
  $myresource = hiera('icingaweb2::config::resource', {})
  create_resources( 'icingaweb2::config::resource', $myresource)

```

role.yaml

```
...
icingaweb2::config::resource:
  'icingaweb2_director_db':
    type: 'db'
    db_type:  'mysql'
    db_name:  "%{hiera('monitoring::icingaweb2_director::mysql_db')}"
    host:  "%{hiera('monitoring::mysql::ipaddress')}"
    port:  3306
    db_charset:  "utf8"
    db_name:  "%{hiera('monitoring::icingaweb2_director::mysql_db')}"
    db_username:  "%{hiera('monitoring::icingaweb2_director::mysql_user')}"
    db_password:  "%{hiera('monitoring::icingaweb2_director::mysql_password')}"
  'myLDAP':
    type: 'ldap'
    port: 398
    ...
```

Is there a better way, like the most common modules, which supports Hiera out-of-the-box ?

cu denny

**Comment by bobapple** [comment]
I understand the use case that you want to add resources by using hiera. What I don't understand is why you don't use the director module and the roles defined type included in this module?

**Comment by linuxmail** [comment]
hi @bobapple 

that's true. I should really change it, but would it make any difference ? The Puppet code changes, but my Hiera problem not :-)
In the end, I have a working Icingaweb2 with the Director module .... Also not shown is the Puppetdb module, which I don't now, how to configure it for more than one PuppetDB.

**Comment by lbetz** [comment]
Then you have to use create_resources or since puppet v4 the new loop and iteration:
https://puppet.com/docs/puppet/5.5/lang_iteration.html

**Comment by lazyfrosch** [comment]
Those hiera create_resources should be handled in a Puppet profile, so they are easily adjustable for local needs.
