### ISSUE TITLE
val.dump in erb file adds escape characters

### ISSUE THREAD

**Issue by gasperno** [Icinga/puppet-icingaweb2#221]
```
   icingaweb2::config::resource{'icinga-auth-ldap':
        type         => 'ldap',
        host         => ‘123.123.123.123’,
        port         => 389,
        ldap_root_dn => 'DC=company,DC=com',
        ldap_bind_dn => ‘domain\username’,
        ldap_bind_pw => ‘password’,
    }
```

The above code snippet creates appropriate ini file section under /etc/icingaweb2/resources.ini but the bind_dn is set as domain\\\\username(note two slashes) because of val.dump in erb file. This leads to invalid credentials for ldap authentication.
https://github.com/Icinga/puppet-icingaweb2/blob/64cf07404cf578bff1c72d4f3d2150a3877d278c/templates/inisection.erb#L7

Any reason for val.dump usage? Any workarounds to override that?

## Expected Behavior

[icinga-auth-ldap]
type = "ldap"
hostname = "123.123.123.123"
port = "389"
root_dn = "DC=company,DC=com"
bind_pw = “password”
encryption = "none"
**bind_dn = "bsa\dev-ops"**
## Current Behavior

[icinga-auth-ldap]
type = "ldap"
hostname = "123.123.123.123"
port = "389"
root_dn = "DC=company,DC=com"
bind_pw = “password”
encryption = "none"
**bind_dn = "bsa\\\\dev-ops"**
## Possible Solution

As explained in summary, val.dump is causing this issue. Is there a specific reason why val.dump is used? val.dump is adding escape characters to special characters in string.
## Steps to Reproduce (for bugs)

1. Include the code snippet in summary
2. It will result in Actual behavior(domain\\\\username) instead of expected behavior(domain\username)

## Context

Trying to connect to LDAP and authenticate with username and password to fetch the users from active directory.
## Your Environment

* Module version (`puppet module list`): v2.2.0
* Puppet version (`puppet -V`): 5.5.8
* Operating System and version: centos7

**Comment by gasperno** [comment]
Hi,
Can you confirm if this is a bug or this is working as expected?

**Comment by lbetz** [comment]
Hi,
sorry I'm late with my answer. The described behavior is expected indeed. It's about ldap because in general the bind_dn doesn't looks like a MS domain connection.

Better choose 'ad' as vlaue for parameter 'type' to connect an Active Directory but you've still to use \\.

**Comment by lazyfrosch** [comment]
You should also probably use the principal name for the user: `dev-ops@bsa.local`

This is the best way for LDAP connections...
