### ISSUE TITLE
Error logging_path needs to be Stdlib::Absolutepath, got String instead

### ISSUE THREAD

**Issue by zilchms** [Icinga/puppet-icingaweb2#224]
I am currently trying to move my Icingaweb2 installation from a manual installation to puppet.
However, when i try to add the icingaweb2 class to my puppet, i get an error stating:
Could not retrieve catalog from remote server: Error 400 on SERVER: Expected parameter 'logging_file' of 'Class[Icingaweb2]' to have type Stdlib::Absolutepath, got String

## Expected Behavior

The installation should run with default settings without getting an error for default set configurations.
## Current Behavior

I have the tried the following configuration. manage_repo is set to false as i already have a working icinga2 installation via puppet running which has set manage_repo to true.
```
class { '::icingaweb2':
    manage_repo   => false,
    import_schema => true,
    db_name       => 'icingaweb2',
    db_username   => 'icingaweb2',
    db_password   => 'supersecret'
  }
´´´
I already tried setting the following settings:
```
logging       => 'none',
logging_file  => '/var/log/icingaweb2/icingaweb2.log',
´´´
Both of those cases fail  with the before mentioned error.

## Steps to Reproduce (for bugs)

1. Install puppet-icingaweb2
2. Run the configuration above

I am however not sure if it is my setup which is wrong or if it is a general problem. I have found no previous issues regarding this behaviour. I am open for any suggestions
## Your Environment

* Module version (`puppet module list`): icinga-icingaweb2  v2.2.0, puppetlabs-vcsrepo v2.4.0, puppetlabs-stdlib v4.20.0, puppetlabs-concat v2.2.1
* Puppet version (`puppet -V`): 3.8.5
* Operating System and version: SUSE Linux Enterprise Server 12 (x86_64), VERSION = 12, PATCHLEVEL = 3

**Comment by lbetz** [comment]
The module puppet-icingaweb2 doesn't support puppet 3. Update to puppet 5.
