### ISSUE TITLE
icingaweb2 module doesn't install php postgres driver when using postgres as backend

### ISSUE THREAD

**Issue by htj** [Icinga/puppet-icingaweb2#228]
When configuring icingaweb2 with the puppet module using postgresql as IDO backend, the php postgresql driver is not installed. The mysql driver is installed though.

This caused a rather weird debug session, as quite a few things doesn't work.

I'd say the module should install the mysql driver if using the mysql backend, and the postgres driver if using the postgresql backend.

On ubuntu the package is called php-pgsql

**Comment by lbetz** [comment]
This module use package dependencies that mean, it isn't a buy here. But you can use the param 'extra_packages' to install extra packages during the installation.
