### ISSUE TITLE
possible regression: new cookie path parameter may break existing installs

### ISSUE THREAD

**Issue by costela** [Icinga/puppet-icingaweb2#235]
## Expected Behavior

Given an icingaweb2 instance with the following simple setup:
```puppet
  class { '::icingaweb2':
    logging             => 'syslog',
    logging_level       => 'INFO',
    logging_facility    => 'local2',
    logging_application => 'icingaweb2',
  }
  icingaweb2::config::authmethod { 'autologin':
    backend  => 'external',
  }
```
Being accessed via a vhost in the form `https://icinga.example.com/`.

That worked with this modules version `<2.3.0`, one would expect it to keep working with `2.3.0`.

## Current Behavior

Clicking on any action (e.g. "Check now") results in:
```
ERROR - Icinga\Web\Form\InvalidCSRFTokenException in /usr/share/php/Icinga/Web/Form/Element/CsrfCounterMeasure.php:64 with message:
#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2280): Icinga\Web\Form\Element\CsrfCounterMeasure->isValid('1183879481|8753...', Array)                                                                 
#1 /usr/share/php/Icinga/Web/Form.php(1276): Zend_Form->isValid(Array)
#2 /usr/share/php/Icinga/Web/Form.php(1150): Icinga\Web\Form->isValid(Array)
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(63): Icinga\Web\Form->handleRequest()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(64): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```

## Root Cause

If the cookie path setting is unset, icingaweb2 [tries to guess the path by default](https://github.com/Icinga/icingaweb2/blob/03d7f3a1f4542880afee19833dde019f65c30612/library/Icinga/Web/Cookie.php#L188) and in this case would correctly use `/` as the cookie path.
As of version 2.3.0, the `cookie_path` parameter was added with `/icingaweb2` as default. This makes icingaweb2 blind to the cookies it sets, making every request generate a new session, and indirectly causing the error above, since the submitted CSRF token doesn't match the new session.

## Possible Solution

Make the new `cookie_path` parameter default to `unset`, leaving it empty per default, as was the behaviour in the previous versions.

## Your Environment

* Module version (`puppet module list`): 2.3.0
* Puppet version (`puppet -V`): 5.5.14
* Operating System and version: Ubuntu 18.04 LTS

**Comment by lazyfrosch** [comment]
I guess you are right, it would be safer not to set the value per default.

**Comment by XnS** [comment]
sorry, did not think about this case :-/
