### ISSUE TITLE
Director 1.7 needs a user & daemon

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/puppet-icingaweb2#246]
## Expected Behavior

Should work out of the box :-)

## Current Behavior

Additional definitions in the profile/role are needed.

https://github.com/Icinga/icinga-vagrant/blob/master/.puppet/modules/profiles/manifests/icinga/icingaweb2.pp#L296

## Possible Solution

Either just document this, or prepare this for systems with systemd.

## Steps to Reproduce (for bugs)

- Use the module to install Icinga Web and Director
- Login & navigate to the Director's Daemon tab

![Screen Shot 2019-09-30 at 14 20 22](https://user-images.githubusercontent.com/382049/66026938-2e39af00-e4fa-11e9-80fd-a30f264a0ef7.png)

## Context

Vagrant boxes.

## Your Environment

* Module version (`puppet module list`): 2.1.0
* Puppet version (`puppet -V`): 5.5.6
* Operating System and version: CentOS 7

**Comment by lbetz** [comment]
refs #250
