### ISSUE TITLE
Class ::icingaweb2::module::monitoring doesn't work with Documentation defaults

### ISSUE THREAD

**Issue by grant-veepshosting** [Icinga/puppet-icingaweb2#253]
1. Use the documentation default configs on Ubuntu 18.04, eg:
```
class profile::icingaweb2 {
  contain ::icingaweb2
  contain ::icingaweb2::module::monitoring
  class { 'icingaweb2::module::monitoring':
    ido_host        => '127.0.0.1',
    ido_db_name     => 'db',
    ido_db_username => 'user',
    ido_db_password => 'thepassword',
    commandtransports => {
      icinga2 => {
        transport => 'api',
        username  => 'root',
        password  => 'icinga',
      }
    }
  }
}
```
-->

## Expected Behavior
It should configure the monitoring source and command transport correctly.

## Current Behavior
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Icingaweb2::Module::Monitoring]: parameter 'commandtransports' expects a Hash value, got Undef (file: /etc/puppetlabs/code/environments/production/site/profile/manifests/icingaweb2.pp, line: 14, column: 3) on node <node>

**Comment by grant-veepshosting** [comment]
UPDATE - we have found the cause and fixed this.

OLD VALUE, BROKEN:
```
class icingaweb2::module::monitoring(
  (other parameters that work fine)
  Hash                           $commandtransports    = undef,
){...
```

NEW VALUE, WORKS:
```
class icingaweb2::module::monitoring(
  (other parameters that work fine)
  Hash                           $commandtransports    = {},
){...
```

**Comment by dnsmichi** [comment]
Hmmm which Puppet version are you using? I've seen a similar behaviour with the MongoDB module where it suddenly expected a value from me.

**Comment by grant-veepshosting** [comment]
Puppet v6 latest. The fix documented above has resolved the issue. The default parameter for the hash needs to be {} instead of undef.
