### ISSUE TITLE
Multiple LDAP Hosts do not work anymore

### ISSUE THREAD

**Issue by formorer** [Icinga/puppet-icingaweb2#261]
The commit 9c66b2df0ba3bb836e862cbc44b55da0a4991123 changed the Host parameter of a resource to `Optional[Stdlib::Host]`, that introduces a regression. For the LDAP Module multiple LDAP Servers separated by spaces are allowed within the Host parameter. Unfortunately that doesn't work anymore.

**Comment by lbetz** [comment]
Thanks, you're right to my knowledge, it is still valid.
