### ISSUE TITLE
Update Package version

### ISSUE THREAD

**Issue by rwaffen** [Icinga/puppet-icingaweb2#262]
Hallo Community,

would it be a good idea to be able to update the icingaweb2 package via puppet/hiera?
Is there a explicit reason to only set it to "installed"?

https://github.com/Icinga/puppet-icingaweb2/blob/ba81a9a01ed8aeb5fea14c6ec5e855e7f8c794e3/manifests/install.pp#L14-L18

**Comment by lbetz** [comment]
Hi Robert,

taht's not the best idea. Puppet is a configuration management tool, software management should be done by other tools like katello, spacewalk, ... or a simple repository and maybe in cooperation with orchestration tools.

Updating software could be a complex process, icingaweb for example has package dependency and optional a database with a schema that could be changed thru an update.

If you really wanna do an update with puppet set manage_package to false and do the package management yourself via resource package before declaring the class icingaweb2.

Bye
Lennart

**Comment by rwaffen** [comment]
Hi Lennart,

Thought it might be a good idea because in many other modules you can handle the package version internally. But when this is your (team) design decision, than it is set.

I will go with the `manage_package` option and manage the version on myself. I like the option to pin/install/update versions in my hiera data.

But thanks for the clarifications.

Greetings.
