### ISSUE TITLE
If import_schema is true then roles.ini file is managed by puppet.

### ISSUE THREAD

**Issue by mamiral** [Icinga/puppet-icingaweb2#263]
Hi,
I really love this module but,
I'm using import_schema TRUE, but i would also like to be able to edit my roles/users from the web itself.
But on each puppet run my roles.ini gets reset.

I've traced it down to the following config.pp lines:
```
  if $import_schema {
    icingaweb2::config::authmethod { "${db_type}-auth":
      backend  => 'db',
      resource => "${db_type}-icingaweb2"
    }

    icingaweb2::config::role { 'default admin user':
      users       => 'icingaadmin',
      permissions => '*',
    }
```
Why in god's name?! ;) Can it be done so that 'default admin user' is optional, or basically that puppet leaves roles.ini file alone even with import_schema is true? That would be great.

Thanks!

br
mm

**Comment by lbetz** [comment]
Hi,

that's unfavorable and of course a bug. As short workaround, after importing for the next puppet run disable the import parameter.

Thx
Lennart

**Comment by lbetz** [comment]
Sorry, I didn't find a solution without a complete redesign. Please use the workaround described above.

**Comment by mamiral** [comment]
Maybe you can create a separate class for 'import schema' code and have a switch 'create default user'.

What I have done, is to disable import schema and I have mimicked your 'import schema' code in my pp class and i have a separate class for adding users into the db (check if user is already in the db). I also copy default roles.ini into /etc/icingaweb2 but i don't control it's contents. It works for ok, you can add/delete users and manage roles from the web.

Thanks again for the module!
