### ISSUE TITLE
manage business process source files

### ISSUE THREAD

**Issue by lelutin** [Icinga/puppet-icingaweb2#265]
Currently this module has a class that can install the `businessprocess` module, but there is no automation for configuring business processes so one is forced to do so in the web interface manually.

From what I could find out, source files are stored in `/etc/icingaweb2/modules/businessprocess/processes/`. So maybe we could drop more source files in there? However, I don't know if more details would be needed in order for the icingaweb2 interface to be aware of those source files and to show them in the web interface.

**Comment by lbetz** [comment]
Hi,

the module classes are indeed supposed to install the module and do a base configuration. If You like to manage processes by puppet you're free to do this by file resources. But keep in mind then GUI and puppet play against each other. This problem also exist for the resource.ini, authentication.ini etc. and I'm not lucky about that.

Bye
Lennart.
