### ISSUE TITLE
PuppetDB throws error

### ISSUE THREAD

**Issue by famfop** [Icinga/puppet-icingaweb2#277]
When running my setup derived from the examples (+README+...) in this repository, Puppet throws the following error message:
```
Error: /Stage[main]/Icingaweb2::Module::Puppetdb/Concat[/etc/icingaweb2/modules/puppetdb/ssl/my_puppetserver.com/private_keys/my_vm.novalocal_combined.pem]/Concat_file[/etc/icingaweb2/modules/puppetdb/ssl/my_puppetserver.com/private_keys/my_vm.novalocal_combined.pem]: Failed to generate additional resources using 'eval_generate': Could not find a directory environment named 'my_environment' anywhere in the path: /etc/puppetlabs/code/environments. Does the directory exist?
Notice: /Stage[main]/Icingaweb2::Module::Puppetdb/Concat[/etc/icingaweb2/modules/puppetdb/ssl/my_puppetserver.com/private_keys/my_vm.novalocal_combined.pem]/File[/etc/icingaweb2/modules/puppetdb/ssl/my_puppetserver.com/private_keys/my_vm.novalocal_combined.pem]/ensure: created
```

where I exchanged names in the obvious locations.

My puppet-icingaweb2 configuration is as follows:
```  
package { 'git': }
include ::mysql::server

class { '::icingaweb2':
  manage_repos  => true,
  import_schema => true,
  db_type       => 'mysql',
  db_host       => 'localhost',
  db_port       => 3306,
  db_username   => 'icingaweb2',
  db_password   => 'icingaweb2',
  config_backend => 'db',
  require       => Mysql::Db['icingaweb2'],
}

icingaweb2::config::resource{'my-sql':
  type        => 'db',
  db_type     => 'mysql',
  host        => 'localhost',
  port        => 3306,
  db_name     => 'icingaweb2',
  db_username => 'icingaweb2',
  db_password => 'icingaweb2',
}

icingaweb2::config::authmethod{'db-auth':
  backend  => 'db',
  resource => 'my-sql',
  order    => '01',
}

mysql::db { 'icingaweb2':
  user     => 'icingaweb2',
  password => 'icingaweb2',
  host     => 'localhost',
  grant    => ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'DROP', 'CREATE VIEW', 'CREATE', 'INDEX', 'EXECUTE', 'ALTER', 'REFERENCES'],
}

# Install modules
class {'icingaweb2::module::monitoring':
  ido_host        => 'localhost',
  ido_db_name     => 'icinga2',
  ido_db_username => 'icinga2',
  ido_db_password => 'superpassword',
  commandtransports => {
    icinga2 => {
      transport => 'api',
      username  => 'director',
      password  => 'directorpassword',
    }
  }
}

class {'icingaweb2::module::director':
  git_revision  => 'master',
  db_host       => 'localhost',
  db_name       => 'director',
  db_username   => 'director',
  db_password   => 'director',
  import_schema => true,
  kickstart     => true,
  endpoint      => 'my_vm.com',
  api_username  => 'director',
  api_password  => 'directorpassword',
  require       => Mysql::Db['director']
}

# double due to deleted endpoint issue
mysql::db { 'director':
  user     => 'director',
  password => 'director',
  host     => 'localhost',
  charset  => 'utf8',
  grant    => ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'DROP', 'CREATE VIEW', 'CREATE', 'INDEX', 'EXECUTE', 'ALTER', 'REFERENCES'],
}

class {'::icingaweb2::module::puppetdb':
  git_revision => 'master',
  ssl          => 'puppet',
  host         => 'my_puppetserver.com',
}
``` 
I have been looking into this error for quite some time but fail to understand. Do you have any idea what could cause the error message? Also, I am not sure if this is sufficient information for you to tell me anything (I'm quite new to icinga and also puppet), so please let me know what else you need. EDIT: I just noticed: The directory _does_ exist on the puppet server but not on the vm (where it seems to be looking for it[?]).

## Possible Solution
I was able to get rid of the error by commenting the `ssl`-line in the `::icingaweb2::module::puppetdb`-call but this does not really help.

## Your Environment
My VM is running Debian 10 and Puppet in version 6. As I was getting another error with the latest version of `puppetlabs-concat`, I selected version 2.0.1 (as in the minimum requirement). Just for completion, here my whole Puppetfile (but not all should be necessary for puppet-icingaweb2):
```
mod 'puppetlabs-stdlib',               :latest
mod 'puppetlabs-apt',                  :latest
mod 'puppetlabs-firewall',             :latest
mod 'puppetlabs-translate',            :latest
mod 'puppet-unattended_upgrades',      :latest
mod 'puppet-logrotate',                :latest
mod 'saz-locales',                     :latest
mod 'nosolutions-tsm',                 :latest
mod 'alexharvey-firewall_multi',       :latest
mod 'icinga-icinga',                   :latest
mod 'icinga-icinga2',                  :latest
mod 'icinga-icingaweb2',               :latest
mod 'puppetlabs-concat',               '2.0.1'
mod 'puppet-zypprepo',                 '2.2.1'
mod 'puppetlabs-vcsrepo',              '1.3.0'
mod 'puppetlabs-apache',               :latest
```

**Comment by lbetz** [comment]
Thx for your report.

But I have no idea if the error
'
Could not find a directory environment named 'my_environment' anywhere in the path: /etc/puppetlabs/code/environments. Does the directory exist?'

isn't the problem. Is the code applied without any errors if you do not declare the puppetdb class?

**Comment by famfop** [comment]
If I do this
```
class {'::icingaweb2::module::puppetdb':
  git_revision => 'master',
#  ssl          => 'puppet',
  host         => 'my_puppetserver.com',
}
```
it does not throw an error. What I did not yet understand is if the module tries to find the environment locally or on the puppet master but I could not find any hint for trying it on the master. Could you explain a bit more detailed what these lines do precisely, please? I did not find the README very clear in this regard.

**Comment by lbetz** [comment]
Ah ok. The parameter 'ssl' is to configure the way how the module is authenticated against the puppetdb. 'puppet' mean, copy the files the puppet agent use to /etc/icingaweb2/modules/puppetdb/ssl.

The prerequisite is that the files (puppet certificate, private key and rootca certificate) already exist.

**Comment by famfop** [comment]
Thank you. I have been looking further into this but without any success. What do you mean by "already exist"? My puppet server does have these files and as far as I understood the 'ssl' parameter set to 'puppet' does collect those from the server. It might be relevant that I furthermore have set the icinga2::feature::api parameter 'pki' to 'puppet'?!

**Comment by lbetz** [comment]
No, icinga2::feature::api has nothing to do with puppetdb.

Authentication against a puppetdb on a dedicated server (not the icingaweb2 host) works via certificate. You need a certificate from your puppet ca in /etc/puppetlabs/puppet/ssl/certs/ on your icingaweb2 host.

**Comment by famfop** [comment]
Ok so I guess this issue is more related to a wrong puppet-icinga2 setup? As you say, the certificates should already exist, but at the same time the puppet-icinga2 setup should already get those files from the server, right?

**Comment by lbetz** [comment]
The puppet-icinga2 comes via puppet, right? You need a functionally puppet master - puppet agent setup, then the puppet certificate is stored in /etc/puppetlabs/puppet/ssl/certs/. The icingaweb2::module::puppetdb uses this certificate and the public key to connect to the puppetdb.

**Comment by famfop** [comment]
I was just editing my previous message. I could find the correct certs in `/var/lib/icinga2/certs/` on my VM, so they got retrieved from the puppet master. So, now I am even more confused.

**Comment by lbetz** [comment]
There a two certificates, one for puppet and one for icinga and signed by two completely different CAs. The puppet certificate is used for communication with the puppet-server by the puppet-agent.
The icinga certificate is for connects between icinga2 instances like master, satellites and agent.

To connect the puppetdb, it's puppet stuff, you've to use the puppet certificate. That mean the icingaweb2::module::puppetdb must use the puppet-agent-certicicate to connect to the puppetdb. The puppet certs in /etc/puppetlabs/puppet/ssl/certs and the public key /etc/puppetlabs/puppet/ssl/private_keys have to exist! And that mean the puppet-master-agent communication must work correctly.

**Comment by famfop** [comment]
Actually they do exist. I was able to fix the error now by setting the $ssl_cert, $ssl_cacert and $ssl_key as base64-strings directly in the icinga2::feature::api config. Not sure why this fails with setting pki to 'puppet' (in the same config), though. But at least it is working for now. Thanks!

**Comment by famfop** [comment]
Hi, as I got everything else running and got more familiar with the whole configuration, I am still confused about this point and I noticed I actually did not fix it back then. Still, my config has the "ssl"-line uncommented, as stated in [this comment](https://github.com/Icinga/puppet-icingaweb2/issues/277#issuecomment-719392033) above. In your (@lbetz) comment right after you explain that these files have to exist. Could you please describe it more in detail or point me to where I can find it by myself? If I do not missunderstand whats keys, certs, etc. are needed, my puppet server does them. And as far as I understand the class, they should get fetched directly from the server?!

**Comment by famfop** [comment]
Hi, as I got everything else running and got more familiar with the whole configuration, I am still confused about this point and I noticed I actually did not fix it back then. Still, my config has the "ssl"-line uncommented, as stated in [this comment](https://github.com/Icinga/puppet-icingaweb2/issues/277#issuecomment-719392033) above. In your (@lbetz) comment right after you explain that these files have to exist. Could you please describe it more in detail or point me to where I can find it by myself? If I do not missunderstand whats keys, certs, etc. are needed, my puppet server does them. And as far as I understand the class, they should get fetched directly from the server?!

**Comment by famfop** [comment]
I was able to get it running with `ssl => 'puppet'` using the latest version of puppetlabs-concat. But to make it work I had to comment the lines 140+141 in the concat's module's init.pp. This feels weird though, so I opened an issue on their ticket-system, where I described it in more detail. You may find the issue [here](https://tickets.puppetlabs.com/browse/MODULES-10872).
