### ISSUE TITLE
Add TLS support to connect mysql database

### ISSUE THREAD

**Issue by lbetz** [Icinga/puppet-icingaweb2#312]
includes support for the connection (icingaweb2/ido backend) and the database (icingaweb2) schema import

**Comment by rychannel** [comment]
I have code that uses the existing icingaweb2::config::resource class that makes this work. We got bit by the lack of support for this functionality so I had to borrow and modify the code.

**Comment by lbetz** [comment]
Sorry @rychannel we'll do a rebuild for the icingadb support.
