### ISSUE TITLE
Add support for navigation items and dashboards

### ISSUE THREAD

**Issue by dgoetz** [Icinga/puppet-icingaweb2#316]
## Expected Behavior
Having support for these config items similar to the already existing ones would be nice. In addition a setting shared or user would be needed for the placement.

## Current Behavior
Not supported yet.

## Possible Solution
Defined resources similar to the existing ones like roles.

## Context
Would be nice to have this more easy configurable than using your own template.

**Comment by lbetz** [comment]
Dashboards are still pending.
