### ISSUE TITLE
Add support for Role permission refusals, parent and unrestricted

### ISSUE THREAD

**Issue by UiP9AV6Y** [Icinga/puppet-icingaweb2#331]
Icingaweb2 [2.9.0](https://github.com/Icinga/icingaweb2/pull/4306) received support for role permissions refusals. the icingaweb2
puppet module however, only supports permission allowances

## Expected Behavior

the icingaweb2 [documentation](https://icinga.com/docs/icinga-web/latest/doc/06-Security/#example) provides the following
example for configuring roles

```ini
[winadmin]
users = "jdoe, janedoe"
groups = "admin"
permissions = "config/*, module/monitoring, monitoring/commands/schedule-check"
refusals = "config/authentication"
monitoring/filter/objects = "host_name=*win*"
```

translating this into puppet would/should result in the following
code

```puppet
icingaweb2::config::role{ 'winadmin':
    users       => 'jdoe, janedoe',
    groups      => 'admin',
    permissions => 'config/*, module/monitoring, monitoring/commands/schedule-check',
    refusals    => 'config/authentication',
    filters     => {
        'monitoring/filter/objects' => 'host_name=*win*'
    }
}
```

given the lack of the *refusals* parameter on the
`icingaweb2::config::role` defined type, the puppet catalog compilation fails

## Current Behavior

role permission refusals cannot be managed with puppet using
this module

## Possible Solution

add an additional parameter to the defined type

## Steps to Reproduce (for bugs)

see example above

## Context

we want to make use of the granular ACL improvements introduced
with icingaweb2 2.9.0

## Your Environment

* puppet-icingaweb2: 3.5.0
* puppet: 7.16
* icingaweb2: 2.11.2

**Comment by lbetz** [comment]
Attributes parent and unrestricted are also missed.

**Comment by leoncard** [comment]
Hello, could you add support for unrestricted as well? The change seems like to only cover refusals.

**Comment by lbetz** [comment]
Overlooked it, done in #337
