### ISSUE TITLE
Set module to absent should only disable the module

### ISSUE THREAD

**Issue by lesinigo** [Icinga/puppet-icingaweb2#336]
## Expected Behavior

When I use `icingaweb2::module { 'something': ensure => absent }` I expected it to completely clean up its stuff from the system

## Current Behavior

If you install an IcingaWeb2 module, for example the grafana one...

```puppet
  icingaweb2::module { 'grafana':
    ensure => present,
    # more config here...
  }
```

...and then proceed to remove it from the system...

```puppet
  icingaweb2::module { 'grafana':
    ensure => absent,
  }
```

...the puppet module will not clean up the config directory:

```
Info: Using environment 'production'
[...]
Warning: /Stage[main]/xxx/Icingaweb2::Module[grafana]/File[/etc/icingaweb2/modules/grafana]: Could not back up file of type directory
Notice: /Stage[main]/xxx/Icingaweb2::Module[grafana]/File[/etc/icingaweb2/modules/grafana]: Not removing directory; use 'force' to override
Notice: /Stage[main]/xxx/Icingaweb2::Module[grafana]/File[/etc/icingaweb2/modules/grafana]/ensure: removed (corrective)
Notice: Applied catalog in 45.55 seconds

$ ls -l /etc/icingaweb2/modules/grafana
total 4
-rw-rw---- 1 www-data icingaweb2 567 Dec 20 15:46 config.ini
```

## Possible Solution

I'd investigate adding `force => true, purge => true, recurse => true` to the [module configuration directory resource](https://github.com/Icinga/puppet-icingaweb2/blob/b15857afa0412434c5c661eb3bd1a9f278406390/manifests/module.pp#L88) and possibly others.

On the other hand, the [documentation about the `ensure` parameter](https://forge.puppetlabs.com/modules/icinga/icingaweb2/3.6.0/reference#ensure-19) clearly says "enable or disable the module" and that does not actually imply removing configuration files, it just "disables" the module. So I'd either investigate implementing actual removal of config files _or_ expand the documentation to explicitly say that those files have to be manually cleared to avoid puppet keep reporting corrective actions at every run.

## Steps to Reproduce (for bugs)

Install a module, remove a module (see above)

## Your Environment

* Module version (`puppet module list`): icinga/icingaweb2 3.6.0
* Puppet version (`puppet -V`): puppet 6.26.0
* Operating System and version: Ubuntu Linux 18.04.6 LTS

**Comment by lbetz** [comment]
Thanks. Ok, that's crap. This is neither one thing nor another. In my opinion, the right way is to just disable the module and keep the config and code. Because when using packages instead of git repos, you haven't any dependencies problems to set ensure to absent. Bit, of course this has to be fixed, one way or the other.

**Comment by lbetz** [comment]
And of course, maybe enable => true | false is the better name for this parameter.

**Comment by lesinigo** [comment]
Yeah if you go for the actual enable/disable route, keeping the files there, I'd suggest to avoid puppet managing the folder (so you don't keep getting corrective changes in your puppet reports) **and** also improve the docs to clarify that files and dirs are gonna stay on the system.
