### ISSUE TITLE
Add manage_package param to do not manage removed icingaweb2-module-monitoring package on Debian and Ubuntu

### ISSUE THREAD

**Issue by mgeerdsen** [Icinga/puppet-icingaweb2#368]
## Expected Behavior

This is nearly the exact same problem as described in #349 

For icingaweb2 >= 2.12.0 icingaweb2::module::monitoring should not install package icingaweb2-module-monitoring on Debian like systems

## Current Behavior

With each Puppet run one of icingaweb2 and icingaweb2-module-monitoring is installed and the other one removed, as there is no icingaweb2-module-monitoring transition package anymore

## Possible Solution

Either a transition package should again be provided or something like #348 should be implemented, so that the module package will not be installed.

## Your Environment
* Module version: 3.9.9
* Puppet version: 6.28.0
* Operating System and version: Ubuntu 20.04 LTS

**Comment by aro-lew** [comment]
I have the same problem.

### Your Environment

- Module version: 3.9.0
- Puppet version: 7.26.0
- Debian 10.13

**Comment by lbetz** [comment]
Yes. Great. They did it again or thought a transition package for just one minor release is enough. I contacted the package maintainer but always waiting for an answer. So I will release a bugfix release with an option to not mange this package on Debian/Ubuntu platforms.

Later, in a major release of puppet-icingaweb2 I will remove the management of icingaweb2-module-monitoring and leave it up to the user to install the package using icingaweb2::extra_packages.
