### ISSUE TITLE
Fix Deprecation-Warning

### ISSUE THREAD

**Issue by cocker-cc** [Icinga/puppet-icingaweb2#381]
Fix the Deprecation-Warning `This function is deprecated, please use stdlib::merge instead.`

**Comment by lbetz** [comment]
Hi,
the current release v3.9.1 only supports stdlib < 9.0.0. I am still working on a new major release v4.0.0 with puppet 8 support and stdlib < 10.0.0. A fix is already merged into the main barnch.
