### ISSUE TITLE
[dev.icinga.com #9154] Add module pnp4nagios

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#53]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9154

**Created by arioch on 2015-04-22 11:51:05 +00:00**

Assignee: _arioch_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-04-22 11:51:55 +00:00 (in Redmine)_

---

**Comment by bobapple** [comment]
Community modules are not handled by this Puppet module anymore. They need to be installed manually by using the `icingaweb2::module`defined type.
