### ISSUE TITLE
[dev.icinga.com #9243] add ldaps to resource_ldap.pp

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#56]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9243

**Created by crpeck on 2015-05-07 16:16:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-05-07 16:16:19 +00:00 (in Redmine)_

---

Could the file manifests/config/resource\_ldap.pp please be extended to include these 2 options:
encryption =&gt; ldaps or ldap (default is ldap)
reqcert =&gt; true or false (default is true) as to if it checks for a valid cert on ldap bind

**Comment by lazyfrosch** [comment]
Fixed by #69
