### ISSUE TITLE
[dev.icinga.com #11507] installing icinga web2 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#57]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11507

**Created by kyle_zeng on 2016-04-01 20:33:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-01 20:33:05 +00:00 (in Redmine)_

---

Hi, I have encountered following problem when I\`m trying to install Icinga web2:

     install icinga2 and mySQL
     install epel
     install icinagweb2 and icinga-cli, at this step, when running :yum install icingaweb2 icingacli

it pops out this error:

> &gt;Error: Package: php-pecl-imagick-2.2.2-5.el6.x86\_64 (epel)
> &gt; Requires: libMagickWand.so.5()(64bit)
> &gt;Error: Package: php-pecl-imagick-2.2.2-5.el6.x86\_64 (epel)
> &gt; Requires: libMagickCore.so.5()(64bit)

and I have tried to install php-imagick but did not solve the problem, and my system is :RHEL6

Could you help me?

**Comment by lazyfrosch** [comment]
Seems like we really need epel on CentOS 6.

Will document it, but can't do much about it, and certainly can't auto-enable EPEL :wink:

See #79

**Comment by walterheck** [comment]
It seems like OP already has epel? Also, from the way he describes his problem it is not at all clear he's actually using puppet?

**Comment by lazyfrosch** [comment]
@walterheck I think you are right.

At least my testing works so far, when you enable EPEL first, then run the module you are fine.

**Comment by walterheck** [comment]
Works for me too, I think we can close this one?

**Comment by lazyfrosch** [comment]
It is already @walterheck
