### ISSUE TITLE
[dev.icinga.com #11584] what is the standard password set by initialize.pp?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#58]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11584

**Created by rwaffen on 2016-04-13 16:44:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-14 11:16:45 +00:00 (in Redmine)_

---

i'm using the puppet module and asking myself, what would be the standard password after "initialization"?

there is no docu about that, only an encrypted password in "puppet-icingaweb2/manifests/initialize.pp".

**Comment by rwaffen** [comment]
This one is fixed and can be closed.
