### ISSUE TITLE
[dev.icinga.com #11719] Missing packages if APT::Install-Recommends "false";

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/puppet-icingaweb2#59]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11719

**Created by plarivee on 2016-05-03 14:07:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-03 14:07:15 +00:00 (in Redmine)_

---

If a system is setup with "APT::Install-Recommends "false";" some packages will not be installed. The module will only install

```
ii  icingaweb2                          2.3.2-1~ppa2                     all          simple and responsive web interface for Icinga
ii  icingaweb2-common                   2.3.2-1~ppa2                     all          simple and responsive web interface for Icinga - common files
ii  php-icinga                          2.3.2-1~ppa2                     all          PHP library to communicate with and use Icinga
```

On a system without the option set to false we get :

```
root@web:~\# dpkg -l | grep icinga
ii icingacli 2.3.2-1~ppa2 all simple CLI tool for Icingaweb2 and its modules
ii icingaweb2 2.3.2-1~ppa2 all simple and responsive web interface for Icinga
ii icingaweb2-common 2.3.2-1~ppa2 all simple and responsive web interface for Icinga - common files
ii icingaweb2-module-doc 2.3.2-1~ppa2 all simple and responsive web interface for Icinga - documentation module
ii icingaweb2-module-monitoring 2.3.2-1~ppa2 all simple and responsive web interface for Icinga - monitoring module
ii php-icinga 2.3.2-1~ppa2 all PHP library to communicate with and use Icinga
```

So the monitoring module package is missing, doc module and also icingacli.

We need to find a way to make sure those are installed if an Icingaweb2 module is dependent of it.

Ubuntu 14.04.4

**Comment by bobapple** [comment]
This is most likely not relevant anymore with the current development.
