### ISSUE TITLE
Adding database initialization

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icingaweb2#64]
Done by @visibilityspots in df99507, 0cc89ec

**Comment by lazyfrosch** [comment]
Also supporting Debian/Ubuntu with 41c46bdf02d4022887d34f32ed91da690240b244

**Comment by lazyfrosch** [comment]
This needs a bit of cleanup, and has a bug in #61

**Comment by visibilityspots** [comment]
The bug has probably been introduced by https://github.com/Icinga/puppet-icingaweb2/commit/41c46bdf02d4022887d34f32ed91da690240b244 when adding the Debian/Ubuntu operating systems. Isn't the fix and cleanup supposed to be handled in that merge request instead?

**Comment by lazyfrosch** [comment]
@visibilityspots I began working on that, haven't pushed it yet, did now if you want to review / test.

**Comment by bobapple** [comment]
See a29902d45e0e2453ae6e3831cc7e72337aa412ad
