### ISSUE TITLE
Improve Apache integration and document it

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icingaweb2#83]
Currently a user needs to add Apache and some modules in order for Icingaweb2 to work.

- [ ] Moving Apache to an extra class `File` conflicts with Apaches files...
- [ ] Add `rewrite` and `php`
- [ ] Add documentation how to configure Apache to work with PHP `mpm_worker => prefork`
- [ ] Document timezone setting for PHP

**Comment by bobapple** [comment]
The current development is not designed to handle apache installation/configuration. This commit 07330520780b7197a05d1b97f121902c3f79222d adds an example how to use Icinga Web 2 and Apache2
