### ISSUE TITLE
Incorrect config directory access mode on Debian

### ISSUE THREAD

**Issue by nilmerg** [Icinga/puppet-icingaweb2#85]
The default access mode is 0755 rather than 2770 as it is for redhat based systems.

**Comment by nilmerg** [comment]
The same applies to the config file mode (0644 instead of 0664)

**Comment by lazyfrosch** [comment]
This is a mistake on Debian based systems:
https://github.com/Icinga/puppet-icingaweb2/blob/master/manifests/params.pp#L79
vs.
https://github.com/Icinga/puppet-icingaweb2/blob/master/manifests/params.pp#L56

**Comment by svojmajstor** [comment]
What about the owner? Is the 'icingaweb2' user legitimate owner/user name by default?

**Comment by bobapple** [comment]
Fixed in master
