### ISSUE TITLE
Dependencies incorrect on Ubuntu 16.04+

### ISSUE THREAD

**Issue by tdb** [Icinga/puppet-icingaweb2#88]
The PHP dependencies are incorrect on Ubuntu 16.04+, specifically this block:

https://github.com/Icinga/puppet-icingaweb2/blob/master/manifests/params.pp#L89

I'd suggest using `php-gd`, etc, instead. This depends on `php7.0-gd`, and will presumably change with future versions as required.

**Comment by lazyfrosch** [comment]
Please use `install_method => 'packages',`

The GIT installation will be deprecated and removed, see #77

**Comment by tdb** [comment]
Yup, now you've merged #87, it's good to use packages. If the git installation is being deprecated this will become a non-issue. Thanks.

**Comment by lazyfrosch** [comment]
Deps should still be fixed :)

**Comment by svojmajstor** [comment]
libapache2-mod-php, should be the one added to the dependencies list

**Comment by bobapple** [comment]
The current development is not designed to handle web server installation/configuration. Therefore I'm closing this issue.
