### ISSUE TITLE
Add Debian Stretch to the compatibility list?

### ISSUE THREAD

**Issue by noobcontrol** [Icinga/puppet-icingaweb2#89]
Hi there,

can you add

Debian Stretch (9.0)

to the module compatibility list?

Greetings and thanks
Tobias

**Comment by bobapple** [comment]
Like the [Icinga2](https://github.com/icinga/puppet-icinga2) module, this module will support LTS versions only.

**Comment by bobapple** [comment]
Wow I was to fast with this, Debian 9 is LTS as well, sorry

**Comment by noobcontrol** [comment]
As Debian 9 is the new stable Debian version you should consider supporting it.
