### ISSUE TITLE
missing groups.ini

### ISSUE THREAD

**Issue by matthiasritter** [Icinga/puppet-icingaweb2#91]
Hi,
I'm missing the configuration for the groups.ini.
If using groups for authentication with ldap:

roles.ini:
[admin-group]
groups = "admin-group"
permissions = "*"
monitoring/hosts/filter = "*"

there has to be a group.ini like:
[icinga_ldap]
user_backend = icingaweb2
backend = msldap
resource = ldap

Maybe I'm wrong? But if not, is it possible to implement this in this puppet-module.

Thanks

**Comment by bobapple** [comment]
This has been added in 29cbce145d6b255752674bb76fe866e9bfceea86
