### ISSUE TITLE
The parameter 'ido_db_host' is declared more than once

### ISSUE THREAD

**Issue by osimon** [Icinga/puppet-icingaweb2#92]
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: The parameter 'ido_db_host' is declared more than once in the parameter list at /etc/puppetlabs/code/environments/production/modules/icingaweb2/manifests/init.pp:181:3 on node client1.XXX.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

**Comment by linuxmail** [comment]
hi,

have the same problem. Installed the module via Puppet. On a older Git clone I don't have the problem.

cu denny

**Comment by linuxmail** [comment]
hi,

as written in other issue. Git und Puppetforge differs. So using the Git version.

**Comment by lrsaigopal** [comment]
Hey @linuxmail can you please let me the version/commit id you are using which solved this problem ?

**Comment by linuxmail** [comment]
hi @lrsaigopal,

this happened after installing Icinga2 module via puppet module install icinga-icinga2. I think, it was one version behind the Github version.
After uninstall and using the git clone ... version, all problems fixed.

cu denny

**Comment by bobapple** [comment]
The current master fixes this
