### ISSUE TITLE
Could not find declared class icingaweb2::mod::monitoring

### ISSUE THREAD

**Issue by osimon** [Icinga/puppet-icingaweb2#93]
Hello,

this is from your example: 
`
# default is local
class { '::icingaweb2::mod::monitoring':
  transport      => 'local',
  transport_path => '/run/icinga2/cmd/icinga2.cmd',
}`

this happens when running:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class icingaweb2::mod::monitoring at /etc/puppetlabs/code/environments/production/modules/icinga2server/manifests/init.pp:64:3 on node clie

I can confirm .. ;)

bla@woody $ ll
total 24
drwxr-xr-x 2 bla bla 4096 Mär  9 15:52 ./
drwxr-xr-x 5 bla bla 4096 Mär  9 16:15 ../
-r--r--r-- 1 bla bla 1177 Apr 23  2015 businessprocess.pp
-r--r--r-- 1 bla bla 1479 Mai  7  2015 deployment.pp
-r--r--r-- 1 bla bla 1846 Apr 23  2015 graphite.pp
-r--r--r-- 1 bla bla 1629 Apr 27  2015 nagvis.pp
.../modules/icingaweb2/manifests/mod
bla@woody $ 

best regards

**Comment by osimon** [comment]
It seems the modules here on github and the one on puppetforge differ .. ?

**Comment by svojmajstor** [comment]
Yes they do

**Comment by linuxmail** [comment]
hi,

yepp. Was my problem too.

**Comment by bobapple** [comment]
Module handling has been refactored in the current master
