### ISSUE TITLE
It would be nice to have possibility to change certain file/directory permissions

### ISSUE THREAD

**Issue by svojmajstor** [Icinga/puppet-icingaweb2#94]
Hello, I may be wrong , but there is no way to change file permissions with hiera.  I tried variations, some like this and many more different, but all I can succeed is change all directories permissions.

`icingaweb2::config_dir:
   '/etc/icingaweb2/enabledModules'
      mode: '777'`

**Comment by bobapple** [comment]
Closing issue since it's most likely not relevant in the current development.
