### ISSUE TITLE
How to enable module monitoring Via Puppet

### ISSUE THREAD

**Issue by svojmajstor** [Icinga/puppet-icingaweb2#95]
Hello, I have installed Icingaweb2 on Ubuntu 16.04 via Puppet. (using Hiera) For some reason module monitoring is not enabled by default (shouldn't it be?). Please help, whatever i try, puppet simply doesn't apply anything. I have fixed file permissions, and still nothing. I have tried something like this:

`icingaweb2::mod::monitoring::transport: 'local'`
`icingaweb2::mod::monitoring::transport_path: '/run/icinga2/cmd/icinga2.cmd'`

**Comment by dnsmichi** [comment]
https://monitoring-portal.org/index.php?thread/40306-no-command-transports-have-been-configured-icingaweb2/

**Comment by bobapple** [comment]
Closing issue since it's not relevant in the current development.
