### ISSUE TITLE
Roles setting is not up to date and is not supporting businessprocess-prefix

### ISSUE THREAD

**Issue by dgoetz** [Icinga/puppet-icingaweb2#96]
The options provided by icingaweb2::config::roles are not up to date for filtering monitoring objects (should be "monitoring/filter/objects") and does not support:
* "application/share/users" and" application/share/groups" for sharing items with users from core
* "monitoring/blacklist/properties" to exclude customvars from monitoring module
* "businessprocess/prefix" from the businessprocess module

**Comment by bobapple** [comment]
Fixed in 70a7874c868c2236456a79ff392c7ef0f867cc98
