### ISSUE TITLE
Non compatible dependencies between icinga2 and Icingaweb2 latest releases

### ISSUE THREAD

**Issue by svojmajstor** [Icinga/puppet-icingaweb2#98]
Puppet module  Icinga2 version 1.2.0 has dependency puppetlabs/concat (>= 2.0.1 < 3.0.0) 
while icingaweb2 version 1.0.6 has dependency puppetlabs/concat (>= 1.2.0 < 2.0.0)

**Comment by lingfish** [comment]
Same here.  I just tried rolling both out, and can't.

**Comment by cfoehrdes** [comment]
puppetlabs/concat has already been remove in the master branch of icingaweb2 but it has not been tagged since a very long time, which was already reported in #141
